# Generated by Django 2.1.8 on 2020-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateOpasswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.CharField(max_length=15)),
                ('server_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('time_stamp', models.CharField(max_length=35)),
                ('time_long', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'estimate_opasswd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NowOpasswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.CharField(max_length=15)),
                ('server_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('time_long', models.CharField(max_length=4)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'now_opasswd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passwdmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.CharField(max_length=15)),
                ('server_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'passwdmanage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=20)),
                ('server_name', models.CharField(blank=True, max_length=50, null=True)),
                ('server_type', models.IntegerField()),
                ('company_name', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
